# Ruff configuration
# https://docs.astral.sh/ruff/

lint.select = ["ALL"]
line-length = 100
target-version = "py314"

[lint.per-file-ignores]
"tests/**" = [
    "T201", # print
    "S101", # assert
    "S106", # hardcoded password
    "PLR2004", # magic values
    "INP001" # implicit namespace package
]

"examples/**" = [
    "INP001", # implicit namespace package
    "T201", # print
    "ERA001", # commented-out code
    "S106" # hardcoded password
]

"src/heroic_discord/typing/**" = ["INP001"]
